<?xml version="1.0" encoding="utf-8" ?>
<!-- List top 5 hits MV in June 2016 -->
<!DOCTYPE top [
<!ELEMENT top (mv+)>
<!ELEMENT mv (Name, Singer, Views, PublishedDate)>
<!ATTLIST mv trackid ID #REQUIRED>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Singer (#PCDATA)>
<!ELEMENT Views (#PCDATA)>
<!ELEMENT PublishedDate (#PCDATA)>
]>
<top>
  <mv trackid="1">
    <Name>Perfect Strangers</Name>
    <Singer>Jonas Blue ft. JP Cooper</Singer>
    <Views>141960678</Views>
    <PublishedDate>2016-14-06</PublishedDate>
  </mv>
  <mv trackid="2">
    <Name>Look alive</Name>
    <Singer>Rae Sremmurd</Singer>
    <Views>26748612</Views>
    <PublishedDate>2016-13-06</PublishedDate>
  </mv>
  <mv trackid="3">
    <Name>Night Riders</Name>
    <Singer>Major Lazer ft. Travis Scott</Singer>
    <Views>11321201</Views>
    <PublishedDate>2016-14-06</PublishedDate>
  </mv>
  <mv trackid="4">
    <Name>Under you</Name>
    <Singer>Nick Jonas</Singer>
    <Views>7147362</Views>
    <PublishedDate>2016-28-06</PublishedDate>
  </mv>
  <mv trackid="5">
    <Name>Bad Intentions</Name>
    <Singer>Niykee Heaton ft. Migos</Singer>
    <Views>1644392</Views>
    <PublishedDate>2016-15-06</PublishedDate>
  </mv>
</top>